name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfile
          push: false
          tags: rag-qantra-docker:latest

      - name: Run tests
        run: |
          docker run --rm rag-qantra-docker:latest python3 -m unittest discover -s tests
